In [1]:
import numpy as np
from scipy.special import logsumexp

In [4]:
T = np.arange(9).reshape(-1, 3)
a = np.arange(3)
print(T.T, a)

[[0 3 6]
 [1 4 7]
 [2 5 8]] [0 1 2]


In [8]:
logsumexp(T.T + a, axis=1)

array([ 8.0184793,  9.0184793, 10.0184793])

In [9]:
T[:, 0]

array([0, 3, 6])

In [22]:
a = np.arange(1, 4)[:, None]
b = np.array([3, 10, 4])[:, None]
print(a @ b.T)

[[ 3 10  4]
 [ 6 20  8]
 [ 9 30 12]]


In [23]:
a, b = np.log(a), np.log(b)

np.exp(a + b.T)

array([[ 3., 10.,  4.],
       [ 6., 20.,  8.],
       [ 9., 30., 12.]])